### ISSUE TITLE
安装不了，2.019

### ISSUE THREAD

**Issue by ycymycym** [mosiboom/dcat-iframe-tab#1]
Fatal error: Uncaught Error: Call to undefined method Dcat\Admin\Admin::extend() in C:\Users\ycym\flyskyedu\vendor\changzhong\extension-iframe-tabs\src\bootstrap.php:4

**Comment by mosiboom** [comment]
\extension-iframe-tabs这个不是我的iframe-tab包，我的iframe-tab包是mosiboom/dcat-iframe-tab
