### ISSUE TITLE
iframe 页面刷新

### ISSUE THREAD

**Issue by howye** [mosiboom/dcat-iframe-tab#14]
iframe 页面刷新后，会直接回到iframe列表页，而不是详情页，请问怎么解决？
![image](https://user-images.githubusercontent.com/26995286/126122022-8880af0f-7633-407f-b4b8-01cd76b68f0c.png)
![image](https://user-images.githubusercontent.com/26995286/126122050-d8c68fa5-896d-4e9c-a547-862dac482eae.png)
![image](https://user-images.githubusercontent.com/26995286/126122078-6b3cd124-2e24-4565-a71a-3c793ab5dcbf.png)
![image](https://user-images.githubusercontent.com/26995286/126122109-c81dc726-dc1e-4a8d-b336-5a2f38574541.png)

**Comment by mosiboom** [comment]
因为我记录的是当前菜单的url，所以没有办法实现你说的功能，除非自己重写一下js代码。如果你想实现二级页面独立刷新，我建议你全局在a标签加上 `iframe-extends=true`和 `iframe-tab=true` 两个属性，把二级页面也添加到标签页中

**Comment by EddiePetter** [comment]
请问在二级页面中如何实现一个可以刷新的按钮？

**Comment by pengwei1986** [comment]
请问，最后怎么解决的
