### ISSUE TITLE
[BUG]表格中的某一行操作按钮下拉菜单出现BUG

### ISSUE THREAD

**Issue by Abbotton** [mosiboom/dcat-iframe-tab#15]
如图所示:
![微信截图_20210721092711](https://user-images.githubusercontent.com/16308633/126416815-bdb35ac2-a9fd-4d03-bd49-cc2e3299a604.png)

现在临时解决办法是修改`config/admin.php`中的`grid.grid_action_class`为`ContextMenuActions::class`或者`Actions::class`.

**Comment by mosiboom** [comment]
请问是怎么出现这个问题的，能具体描述一下吗

**Comment by Abbotton** [comment]
请看动画, Dcat-admin版本是`2.1.1-beta`

![动画](https://user-images.githubusercontent.com/16308633/126461849-9e75121b-30a9-4581-9867-58c6c197e9bb.gif)

**Comment by Abbotton** [comment]
在`<table>`标签上加上`overflow:hidden !important;`可以去掉左右和上下的滚动条,但弹出来的下拉菜单也被隐藏掉了.

**Comment by mosiboom** [comment]
看一下iframe-tab的版本

**Comment by Abbotton** [comment]
> 看一下iframe-tab的版本

![image](https://user-images.githubusercontent.com/16308633/126463475-1efb423d-5fb7-445c-8519-47035760e97b.png)

**Comment by mosiboom** [comment]
我用了原来这个配置也是没有问题的，`Dcat\Admin\Grid\Displayers\DropdownActions::class`，而且我把屏幕尺寸调小也没能出现你这个问题，之前在`1.1.1`版本的时候已经修复了表格内容过多时造成横向滚动条无法移动的问题，可以看下版本更新日志：

**Comment by mosiboom** [comment]
我用了原来这个配置也是没有问题的，Dcat\Admin\Grid\Displayers\DropdownActions::class，而且我把屏幕尺寸调小也没能出现你这个问题，之前在1.1.1版本的时候已经修复了表格内容过多时造成横向滚动条无法移动的问题，可以看下版本更新文档：
[dcat-iframe-tab/releases/tag/1.1.1](https://github.com/mosiboom/dcat-iframe-tab/releases/tag/1.1.1)

![image](https://user-images.githubusercontent.com/33051181/126464973-d62f382f-2a18-4835-ae73-87c44357c101.png)

**Comment by mosiboom** [comment]
或者尝试着ctrl+F5无缓存刷新下页面

**Comment by Abbotton** [comment]
我看了下PR记录，感觉还是[这段CSS代码](https://github.com/mosiboom/dcat-iframe-tab/commit/204315f48998bf53dfd91168fc267734ad702e60#diff-c1dbf830efe711df351a94b36b52a1fd4b1bc3cd15548ec6bff0bf7bce724fa4R31-R33)的问题：
```css
#app .dcat-box{
    overflow: auto;
}
```

我修改为如下代码就正常了:
```css
#app .dcat-box{
    overflow: revert;
}
```
动画如下:
![演示](https://user-images.githubusercontent.com/16308633/126470227-51a0623b-e7e6-4d0e-8d47-0e3e8d3f1514.gif)

您再帮忙看一下, 如果确实是这个问题, 那就简单了, 您这边提个PR就完事儿了.

PS: 我的浏览器是`Microsoft Edge v91.0.864.70`, 也在别的电脑上使用`Firefox v89.0.2 `测试过.

**Comment by mosiboom** [comment]
应该是这个问题。我这边测试了下只有chrome能成功，Safari上也不行，感谢您提的问题，稍后我会修改发布新版本，能顺便科普下`revert`这个属性值吗

**Comment by mosiboom** [comment]
[revertMDN文档](https://developer.mozilla.org/en-US/docs/Web/CSS/revert)

**Comment by Abbotton** [comment]
> 应该是这个问题。我这边测试了下只有chrome能成功，Safari上也不行，感谢您提的问题，稍后我会修改发布新版本，能顺便科普下`revert`这个属性值吗

哈哈, 科普谈不上, 您这已经贴了链接了. 我就不献丑了. 期待发新版.

**Comment by Abbotton** [comment]
更新了一下,实测确实已解决这个问题.谢谢.
