### ISSUE TITLE
子域名模式下出现后台无限套娃

### ISSUE THREAD

**Issue by Abbotton** [mosiboom/dcat-iframe-tab#17]
已经尝试修改配置文件中的`domain`项，但没有解决问题。
如下图：
![image](https://user-images.githubusercontent.com/16308633/129881466-55e2d3d5-62c0-40de-b392-d7e41f5d8ed1.png)

**Comment by mosiboom** [comment]
[参考链接1](https://github.com/mosiboom/dcat-iframe-tab/issues/9)

[参考链接2](https://github.com/mosiboom/dcat-iframe-tab/issues/2)

**Comment by Abbotton** [comment]
配置问题。不好意思。
