### ISSUE TITLE
安装完成后首页有问题

### ISSUE THREAD

**Issue by yb-ben** [mosiboom/dcat-iframe-tab#2]
![image](https://user-images.githubusercontent.com/26037615/112108349-09a02e00-8beb-11eb-9c65-38a77a17bdfb.png)
安装完成后首页有问题

**Comment by michelleyaoyao** [comment]
是的。我也安装了。 首页有问题。 不知道怎么解决。谢谢

**Comment by mosiboom** [comment]
首页有问题是因为iframe-tab占用了你默认的根路由，也就是“/”，你应该把主页的路由更改为“/dashboard”或者其他

**Comment by dmskys** [comment]
> 首页有问题是因为iframe-tab占用了你默认的根路由，也就是“/”，你应该把主页的路由更改为“/dashboard”或者其他

我把我的主页路由改成dashboard后，首页也跟他们一样，麻烦辛苦看看

**Comment by dmskys** [comment]
> 首页有问题是因为iframe-tab占用了你默认的根路由，也就是“/”，你应该把主页的路由更改为“/dashboard”或者其他

我把我的主页路由改成dashboard后，首页也跟他们一样，麻烦辛苦看看

**Comment by dmskys** [comment]
> 首页有问题是因为iframe-tab占用了你默认的根路由，也就是“/”，你应该把主页的路由更改为“/dashboard”或者其他

而且还发现一个问题，就是在后台使用独立域名部署的时候、不使用/admin 目录访问时，无法找到你的iframe主页路由

**Comment by mosiboom** [comment]
> 我把我的主页路由改成dashboard后，首页也跟他们一样，麻烦辛苦看看

你能贴一下你的路由代码和截图吗。

**Comment by mosiboom** [comment]
> 而且还发现一个问题，就是在后台使用独立域名部署的时候、不使用/admin 目录访问时，无法找到你的iframe主页路由

我不是很明白您说的这个问题。我在后面会更新一个能够自己配置路由的版本，可以让使用者自定义配置路由

**Comment by dmskys** [comment]
> > 我把我的主页路由改成dashboard后，首页也跟他们一样，麻烦辛苦看看
> 
> 你能贴一下你的路由代码和截图吗。

说明一下：图1，是我原来的展示，首页显示仪表盘数据
![3](https://user-images.githubusercontent.com/5857415/112811045-3bfbd080-90ae-11eb-95f9-a51b4c778ac0.jpg)
图2，是我原来的路由配置
![1](https://user-images.githubusercontent.com/5857415/112811096-49b15600-90ae-11eb-93de-106c5751c12b.jpg)
图3，是我使用iframe改变后的路由配置，
![Uploading 2.jpg…]()

**Comment by dmskys** [comment]
终于解决需要设置菜单的首页地址为 /dashboard 并配置原来的首页路由为/dashboard

**Comment by pengwei1986** [comment]
> 终于解决需要设置菜单的首页地址为 /dashboard 并配置原来的首页路由为/dashboard

您好，是怎么解决的？

**Comment by coderdavi** [comment]
> > 终于解决需要设置菜单的首页地址为 /dashboard 并配置原来的首页路由为/dashboard
> 
> 您好，是怎么解决的？

1.修改routes.php中首页路径$router->get('/index', 'HomeController@index');
2.修改菜单栏中index对应得理由为/index

**Comment by dxmq** [comment]
点右边面包屑导航的“主页”时，页面显示空白，请问一下如何解决？
![image](https://user-images.githubusercontent.com/43381204/220097561-292f5afc-4871-4818-83b8-2255db00f636.png)

**Comment by aogg** [comment]
```
Route::group([
    'prefix'     => config('admin.route.prefix'),
    'namespace'  => config('admin.route.namespace'),
    'middleware' => config('admin.route.middleware'),
], function (Router $router) {

    $router->get('/index', 'HomeController@index');

});
```

UPDATE `laravel`.`admin_menu` SET `uri` = '/index' WHERE `id` = 1
