### ISSUE TITLE
iframe 加载能支持加载动画吗

### ISSUE THREAD

**Issue by sonhineboy** [mosiboom/dcat-iframe-tab#22]
iframe 加载能支持加载动画吗

**Comment by mosiboom** [comment]
什么意思呢，具体说说

**Comment by sonhineboy** [comment]
就是iframe 加载的页面比较耗时了，显示loading 动画，当页面加载完成了取消动画显示页面信息

**Comment by mosiboom** [comment]
您可以开启懒加载模式，开启懒加载的话是只加载当前的子页面，不会同时加载其他在tab栏的页面。如果是全局的loading的话是没有加的

**Comment by sonhineboy** [comment]
懒加载是默认开始的，那作者这个iframe loading 这个是不是考虑后期升级加上这个效果，体现会更好点

**Comment by mosiboom** [comment]
后面可以考虑加下😁
