### ISSUE TITLE
做跳转的时候 会生成新的tab的同时原先页面和新生成的页面一摸一样

### ISSUE THREAD

**Issue by candivan** [mosiboom/dcat-iframe-tab#23]
$grid->column('uid')->display(function () {
                $url = "/admin/user?id=" . $this->uid;
                return "<a iframe-extends=true iframe-tab=true href='$url' title=''>{$this->uid}</a>";
     });

点击跳转的时候 这个页面和用户页面会变成一样

**Comment by mosiboom** [comment]
截一下图吧，我不太清楚您的意思

**Comment by candivan** [comment]
就是在A页面做一个链接跳转到B页面。这时候A页面变成和B页面一样
```
$url = "/admin/user?id=" . $this->rid;
return "<a iframe-extends=true iframe-tab=false href='$url' title=''>{$this->rid}</a>";
```

**Comment by mosiboom** [comment]
您的意思是，他没有跳转到对应用户的信息吗？也就是
`"/admin/user?id=" . $this->rid;`
?

**Comment by candivan** [comment]
> 截一下图吧，我不太清楚您的意思



> 您的意思是，他没有跳转到对应用户的信息吗？也就是 `"/admin/user?id=" . $this->rid;` ?

跳到了 但是之前的页面也变成用户信息页面了

**Comment by mosiboom** [comment]
尝试一下这样：
`<a iframe-extends=true iframe-tab=true href='$url' title=''>{$this->rid}</a>`
文档有写的，这个属性`iframe-tab=true`开启一下：

![image](https://user-images.githubusercontent.com/33051181/145141394-47e66a73-bc84-4076-9f47-d6842101d360.png)

**Comment by candivan** [comment]
> 尝试一下这样： `<a iframe-extends=true iframe-tab=true href='$url' title=''>{$this->rid}</a>` 文档有写的，这个属性`iframe-tab=true`开启一下：
> 
> ![image](https://user-images.githubusercontent.com/33051181/145141394-47e66a73-bc84-4076-9f47-d6842101d360.png)

一样的

**Comment by mosiboom** [comment]
检查一下js，看看是否有冒泡事件产生，我默认是把a链接的跳转事件禁用了的，正常来说是不会有什么问题，可能是由于您的某些操作覆盖了默认的冒泡事件，可以看下源码:
`src/assets/js/extend.js/`

**Comment by candivan** [comment]
> 检查一下js，看看是否有冒泡事件产生，我默认是把a链接的跳转事件禁用了的，正常来说是不会有什么问题，可能是由于您的某些操作覆盖了默认的冒泡事件，可以看下源码: `src/assets/js/extend.js/`

`<a iframe-extends=true iframe-tab=true href='$url' title='' target='_blank'>{$this->rid}</a> `  加了target='_blank'就可以了

**Comment by candivan** [comment]
> 检查一下js，看看是否有冒泡事件产生，我默认是把a链接的跳转事件禁用了的，正常来说是不会有什么问题，可能是由于您的某些操作覆盖了默认的冒泡事件，可以看下源码: `src/assets/js/extend.js/`

你文档可以补一下 target='_blank'
