### ISSUE TITLE
能不能支持php7.1?

### ISSUE THREAD

**Issue by xiaojian520** [mosiboom/dcat-iframe-tab#27]

**Comment by mosiboom** [comment]
这个跟PHP版本没关系的，主要是跟Laravel版本和Dcat的版本有关

**Comment by xiaojian520** [comment]
> 这个跟PHP版本没关系的，主要是跟Laravel版本和Dcat的版本有关

你得composer.json限制了php>=7.2.5, 所以我7.1安装的时候提示php版本必须大于7.2.5
