### ISSUE TITLE
希望添加独立域名配置

### ISSUE THREAD

**Issue by dmskys** [mosiboom/dcat-iframe-tab#3]
use Mosiboom\DcatIframeTab\Controllers\IframeController;

if (config('iframe_tab.enable')) {
    $attributes = [
        'prefix' => config('admin.route.prefix'),
        'middleware' => config('admin.route.middleware'),
    ];
    app('router')->group($attributes, function ($router) {
        $controller = IframeController::class;
        $router->get('/', $controller . '@index');
    });
}

希望添加独立域名配置：
'domain' => config('admin.route.domain', null),

**Comment by mosiboom** [comment]
是的，我后面会加，谢谢您的建议
