### ISSUE TITLE
IE浏览器有兼容问题

### ISSUE THREAD

**Issue by pengwei1986** [mosiboom/dcat-iframe-tab#4]
SCRIPT1003: 缺少 ':'
 /*定义模板*/
    const iframeTabTemplate = {
        **tabItem(html, id, use_close = true) {**
            /*标签栏*/
            let close_html = ''
            let first_tag = 'data-first=1'
            if (use_close) {
                close_html = '<span title="关闭标签页" class="iframe-tab-close-btn"><i class="fa fa-minus-circle"></i></span>'
                first_tag = 'data-first=0'
            }
            return `
            <li class="nav-item swiper-slide" role="presentation">
                    <a ${first_tag} class="nav-link active" id="iframe-home-${id}" data-toggle="pill" href="#iframe-${id}" role="tab" aria-controls="iframe-${id}" aria-selected="true">
                        ${html}
                        ${close_html}
                    </a>
            </li>
            `
        },

**Comment by mosiboom** [comment]
这边不是专门做前端的，对兼容性研究并不是很多，建议使用谷歌浏览器。或者自己手动改

**Comment by mosiboom** [comment]
你好，对于兼容性问题，我感觉是因为在js中使用了es6语法，IE浏览器对ES 6 语法并不够兼容，所以可以使用一些前端工具转换一下，这部分内容在下个版本我会发一个转换es5版本的js
