### ISSUE TITLE
后台主页无限套娃

### ISSUE THREAD

**Issue by TELstatic** [mosiboom/dcat-iframe-tab#9]
如题

地址 /admin

**Comment by mosiboom** [comment]
修改主页菜单的路由地址。比如默认是 `/admin`，那就改成 `/admin/dashboard` ，或者是去`config/iframe_tab.php`配置文件中配置iframe-tab的默认占用路由

**Comment by TELstatic** [comment]
新问题 刚刚那个已解决
![image](https://user-images.githubusercontent.com/18006395/120737558-df3eeb00-c520-11eb-8c4c-fdf52afadcb1.png)

**Comment by mosiboom** [comment]
dialog窗口调整readme.md最后面的配置有：
![image](https://user-images.githubusercontent.com/33051181/120737929-8c196800-c521-11eb-9fce-457e44fc9df0.png)
使用前请先看文档！

**Comment by TELstatic** [comment]
好的 谢谢

**Comment by TELstatic** [comment]
上述修改的配置 没有影响到 分类快捷编辑

因为源代码 Dcat\Admin\Tree\Actions\QuickEdit 指定了 宽高

**Comment by jackchang1025** [comment]
> 修改主页菜单的路由地址。比如默认是 `/admin`，那就改成 `/admin/dashboard` ，或者是去`config/iframe_tab.php`配置文件中配置iframe-tab的默认占用路由

![image](https://user-images.githubusercontent.com/71494064/154605141-ccc529dc-180a-4624-9ea3-f53dd3ff12d6.png)
![image](https://user-images.githubusercontent.com/71494064/154605400-eecfe159-5c4d-4f7c-9893-c13fe7c9eb2a.png)

修改了配置文件的默认路由，显示如上图

**Comment by jackchang1025** [comment]
版本是2.1.7的
